import typing

from BaseClasses import Location
from .Names import LocationName, ItemName


class OT2Location(Location):
    game: str = "Octopath 2"


class LocationData(typing.NamedTuple):
    region: str = None


Totohaha_Checks={   
    LocationName.BeastingVillage1800L:                              LocationData("Beasting Village"),
    LocationName.BeastingVillageGiantBow:                           LocationData("Beasting Village"),
    LocationName.BeastingVillageResistantNutL:                      LocationData("Beasting Village"),
    LocationName.BeastingVillagePerfectJerky:                       LocationData("Beasting Village"),
    LocationName.BeastingVillageReinforcingJam:                     LocationData("Beasting Village"),
    LocationName.PathtotheTombsoftheWardenbeastsUnerringRing:       LocationData("Path to the Tombs of the Wardenbeasts"),
    LocationName.PathtotheTombsoftheWardenbeastsInspiritingPlum:    LocationData("Path to the Tombs of the Wardenbeasts"),
    LocationName.PathtotheTombsoftheWardenbeastsJerky:              LocationData("Path to the Tombs of the Wardenbeasts"),
    LocationName.TombsoftheWardenbestsCompositeBow:                 LocationData("Tombs of the Wardenbests"),
    LocationName.TombsoftheWardenbestsBone:                         LocationData("Tombs of the Wardenbests"),
    LocationName.TombsoftheWardenbestsSharpNut:                     LocationData("Tombs of the Wardenbests"),
    LocationName.NorthBeastingTraverseInspiritingPlumM:             LocationData("North Beasting Traverse"),
    LocationName.NorthBeastingTraverseEmpoweringLychee:             LocationData("North Beasting Traverse"),
    LocationName.NorthBeastingTraverseWindSoulstone:                LocationData("North Beasting Traverse"),
    LocationName.NorthBeastingTraverseWarAxe:                       LocationData("North Beasting Traverse"),
    LocationName.BeastingBayAnchorageSlumberSage:                   LocationData("Beasting Bay: Anchorage"),
    LocationName.BeastingBayAnchorageHealingGrapeM:                 LocationData("Beasting Bay: Anchorage"),
    LocationName.WesternTropuHopuTraverseEmpoweringLychee:          LocationData("Western TropuHopu Traverse"),
    LocationName.WesternTropuHopuTraverseQualityJerky:              LocationData("Western TropuHopu Traverse"),
    LocationName.WesternTropuHopuTraverseLightSoulstoneM:           LocationData("Western TropuHopu Traverse"),
    LocationName.WesternTropuHopuTraverseSprightlyBracelet:         LocationData("Western TropuHopu Traverse"),
    LocationName.WesternTropuHopuTraverseHealingGrapeBunch:         LocationData("Western TropuHopu Traverse"),
    LocationName.TropuHopuEnergizingPomegranateM:                   LocationData("TropuHopu"),
    LocationName.TropuHopuCaitPowder:                               LocationData("TropuHopu"),
    LocationName.TropuHopuPrettyPearl:                              LocationData("TropuHopu"),
    LocationName.TropuHopuSkullHelm:                                LocationData("TropuHopu"),
    LocationName.TropuHopuShipyeardEmpoweringLycheeM:               LocationData("TropuHopu: Shipyeard"),
    LocationName.TropuHopuFloatingTheaterInspiritingPlumM:          LocationData("TropuHopu: Floating Theater"),
    LocationName.SouthernNamelessVillageTraverseSuperiorJerky:      LocationData("Southern Nameless Village Traverse"),
    LocationName.SouthernNamelessVillageTraverseHerbofSerenity:     LocationData("Southern Nameless Village Traverse"),
    LocationName.SouthernNamelessVillageTraverseWindSoulstoneL:     LocationData("Southern Nameless Village Traverse"),
    LocationName.SouthernNamelessVillageTraverseMentalBelt:         LocationData("Southern Nameless Village Traverse"),
    LocationName.NamelessVillageMythicalHorn:                       LocationData("Nameless Village"),
    LocationName.NamelessVillageEmpoweringLycheeM:                  LocationData("Nameless Village"),
    LocationName.NamelessVillageSaltedSeafood:                      LocationData("Nameless Village"),
    LocationName.NamelessVillageStimulatingNecklace:                LocationData("Nameless Village"),
    LocationName.NamelessVillageBottleofBefuddlingDust:             LocationData("Nameless Village"),
    LocationName.NamelessVillageForbiddenBow:                       LocationData("Nameless Village"),
    LocationName.WanderingWoodAntiqueCeremonialMask:                LocationData("Wandering Wood"),
    LocationName.WanderingWoodInspiritingPlumM:                     LocationData("Wandering Wood"),
    LocationName.WanderingWoodHealingGrapeBunch:                    LocationData("Wandering Wood"),
    LocationName.WanderingWood28000L:                               LocationData("Wandering Wood"),
    LocationName.WanderingWoodLightSoulstoneL:                      LocationData("Wandering Wood"),
    # LocationName.ShirlutoJerky:                                   LocationData("Wandering Wood"),
    LocationName.RiftedRockRevitalizingJam:                         LocationData("Rifted Rock"),
    LocationName.RiftedRockHallowedRod:                             LocationData("Rifted Rock"),
    LocationName.RiftedRockVoidAmulet:                              LocationData("Rifted Rock"),
    LocationName.VerdantWoodEnergizingPomegranateL:                 LocationData("Verdant Wood"),
    LocationName.StormyCapeAxeoftheConqueror:                       LocationData("Stormy Cape"),
    LocationName.StormyCapeRevitalizingJam:                         LocationData("Stormy Cape"),
    LocationName.StormyCapeTornadoBow:                              LocationData("Stormy Cape"),
    LocationName.StormyCapeEmpoweringLycheeL:                       LocationData("Stormy Cape"),
    LocationName.SinkingRuinsPerfectJerky:                          LocationData("Sinking Ruins"),
    LocationName.SinkingRuinsArticulateStone:                       LocationData("Sinking Ruins"),
    LocationName.SinkingRuinsHerbofGraceBud:                        LocationData("Sinking Ruins"),
    LocationName.SinkingRuins30000L:                                LocationData("Sinking Ruins"),
    LocationName.SinkingRuinsSeaGodsSpear:                          LocationData("Sinking Ruins"),
    LocationName.SinkingRuinsRustyBow:                              LocationData("Sinking Ruins"),
    LocationName.CavernofWavesSaltedSeafood:                        LocationData("Cavern of Waves"),
    LocationName.CavernofWavesHealingGrapeBunch:                    LocationData("Cavern of Waves"),
    LocationName.CavernofWavesOliveofLifeL:                         LocationData("Cavern of Waves"),
    LocationName.CavernofWavesJPAugmentor:                          LocationData("Cavern of Waves"),
    LocationName.CavernofWavesRagingBeast:                          LocationData("Cavern of Waves"),
    LocationName.CavernofWavesRuinousRelic1:                        LocationData("Cavern of Waves"),
    LocationName.CavernofWavesRuinousRelic2:                        LocationData("Cavern of Waves"),
    LocationName.CavernofWavesRuinousRelic3:                        LocationData("Cavern of Waves"),

}

Harborlands_Checks={
    LocationName.CanalbrineResistantNut:                            LocationData("Canalbrine"),
    LocationName.CanalbrineSlumberSage:                             LocationData("Canalbrine"),
    LocationName.CanalbrineWoodcuttersGreatAxe:                     LocationData("Canalbrine"),
    LocationName.CanalbrinePathtotheWaterSourceDarkdelion:          LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrinePathtotheWaterSourceEmpoweringRing:      LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrinePathtotheWaterSourcePlumLeaf:            LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrinePathtotheWaterSourceGrapeLeaf:           LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrinePathtotheWaterSourceGuardsHelm:          LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrinePathtotheWaterSourceHerbofHealing:       LocationData("Canalbrine: Path to the Water Source"),
    LocationName.CanalbrineWaterSourceDiffusingSerum:               LocationData("Canalbrine: Water Source"),
    LocationName.CanalbrineWaterSourceCleansingLeaf:                LocationData("Canalbrine: Water Source"),
    LocationName.CanalbrineWaterSourceOldArmor:                     LocationData("Canalbrine: Water Source"),
    LocationName.CanalbrineWaterSourceHerbofHealing:                LocationData("Canalbrine: Water Source"),
    LocationName.WesternCanalbrineCoastHealingGrapeM:               LocationData("Western Canalbrine Coast"),
    LocationName.WesternCanalbrineCoastHerbofSerenity:              LocationData("Western Canalbrine Coast"),
    LocationName.WesternCanalbrineCoastTravelersBow:                LocationData("Western Canalbrine Coast"),
    LocationName.WesternCanalbrineCoastInspiritingPlumM:            LocationData("Western Canalbrine Coast"),
    LocationName.WesternCanalbrineCoast1500L:                       LocationData("Western Canalbrine Coast"),
    LocationName.WesternCanalbrineCoastStickyFlower:                LocationData("Western Canalbrine Coast"),
    LocationName.CanalbrineBridgeCleansingLeaf:                     LocationData("Canalbrine Bridge"),
    LocationName.CanalbrineBridgeSilverSword:                       LocationData("Canalbrine Bridge"),
    LocationName.CanalbrineBridgeHealingGrapeBunch:                 LocationData("Canalbrine Bridge"),
    LocationName.CanalbrineBridgeIceSoulstone:                      LocationData("Canalbrine Bridge"),
    LocationName.CanalbrineBridgeLance:                             LocationData("Canalbrine Bridge"),
    LocationName.CanalbrineBridgeRefreshingJam:                     LocationData("Canalbrine Bridge"),
    LocationName.SacredGuardShipMace:                               LocationData("Sacred Guard Ship"),
    LocationName.SacredGuardShipInspiritingPlumM:                   LocationData("Sacred Guard Ship"),
    LocationName.SacredGuardShip5600L:                              LocationData("Sacred Guard Ship"),
    LocationName.SacredGuardShipDarkAmulet:                         LocationData("Sacred Guard Ship"),
    LocationName.SacredGuardShipEmpoweringLycheeM:                  LocationData("Sacred Guard Ship"),
    LocationName.NorthernConningCreekCoastEnergizingPomegranate:    LocationData("Northern Conning Creek Coast"),
    LocationName.NorthernConningCreekCoastMatchingTrident:          LocationData("Northern Conning Creek Coast"),
    LocationName.NorthernConningCreekCoastWindSoulstoneM:           LocationData("Northern Conning Creek Coast"),
    LocationName.NorthernConningCreekCoastHelmcleaver:              LocationData("Northern Conning Creek Coast"),
    LocationName.WesternConningCreekCoastEmpoweringLychee:          LocationData("Western Conning Creek Coast"),
    LocationName.WesternConningCreekCoastUnerringBracelet:          LocationData("Western Conning Creek Coast"),
    LocationName.WesternConningCreekCoastSlumberSage:               LocationData("Western Conning Creek Coast"),
    LocationName.WesternConningCreekCoastEnergizingPomegranate:     LocationData("Western Conning Creek Coast"),
    LocationName.ConningCreekBottleofBefuddlingDust:                LocationData("Conning Creek"),
    LocationName.ConningCreekBlazonofProtection:                    LocationData("Conning Creek"),
    LocationName.ConningCreekOutskirtsInspiritingPlumM:             LocationData("Conning Creek: Outskirts"),
    LocationName.ConningCreekOutskirtsFireSoulstoneM:               LocationData("Conning Creek: Outskirts"),
    LocationName.ConningCreekHarborRainbowGlassBottle:              LocationData("Conning Creek: Harbor"),
    LocationName.CavernoftheSeaGodEmpoweringLycheeM:                LocationData("Cavern of the Sea God"),
    LocationName.CavernoftheSeaGodRabbitShield:                     LocationData("Cavern of the Sea God"),
    LocationName.CavernoftheSeaGodHealingGrapeBunch:                LocationData("Cavern of the Sea God"),
    LocationName.CavernoftheSeaGod6000L:                            LocationData("Cavern of the Sea God"),
    LocationName.GuardOutpostFireSoulstone:                         LocationData("Guard Outpost"),
    LocationName.GuardOutpostGuardsArmor:                           LocationData("Guard Outpost"),
    LocationName.GuardOutpostEmpoweringLycheeM:                     LocationData("Guard Outpost"),
    LocationName.GuardOutpostGuardsHat:                             LocationData("Guard Outpost"),
    LocationName.GuardOutpost7200L:                                 LocationData("Guard Outpost"),
    LocationName.LairoftheUsurperBottleofSleepingDust:              LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurperThunderMace:                       LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurperOliveofLifeL:                      LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurperGrailofLife:                       LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurper6500L:                             LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurperWeatheredTreasureShield:           LocationData("Lair of the Usurper"),
    LocationName.LairoftheUsurperEmpoweringLycheeL:                 LocationData("Lair of the Usurper"),
    LocationName.CavernoftheMoonandSun2400L:                        LocationData("Cavern of the Moon and Sun"),
    LocationName.CavernoftheMoonandSunMightyBelt:                   LocationData("Cavern of the Moon and Sun"),
    LocationName.CavernoftheMoonandSunLightSoulstoneL:              LocationData("Cavern of the Moon and Sun"),
    LocationName.RoqueIslandAnchorage22000L:                        LocationData("Roque Island: Anchorage"),
    LocationName.RoqueIslandAnchorageEnlighteningNecklace:          LocationData("Roque Island: Anchorage"),
    LocationName.RoqueIslandAnchorageHealingGrapeBunch:             LocationData("Roque Island: Anchorage"),
    LocationName.RoqueIslandEmpoweringLycheeL:                      LocationData("Roque Island"),
    LocationName.RoqueIsland39800L:                                 LocationData("Roque Island"),
    LocationName.RoqueIslandRejuvenatingJam1:                       LocationData("Roque Island"),
    LocationName.RoqueIslandRejuvenatingJam2:                       LocationData("Roque Island"),
    LocationName.RoqueIslandRejuvenatingJam3:                       LocationData("Roque Island"),
    LocationName.RoqueIslandMagicNutL:                              LocationData("Roque Island"),
    LocationName.RoqueIslandHerbofHealing:                          LocationData("Roque Island"),
    LocationName.RoqueIslandEnergizingPomegranateL:                 LocationData("Roque Island"),
    LocationName.RoqueIslandHeadquartersCriticalBracelet:           LocationData("Roque Island: Headquarters"),
    LocationName.TheRoqueCompanyWestTowerInspiritingPlumBasket:     LocationData("The Roque Company: West Tower"),
    LocationName.TheRoqueCompanyWestTowerEmpoweringLycheeL:         LocationData("The Roque Company: West Tower"),
    LocationName.TheRoqueCompanyWestTowerFireSoulstoneL:            LocationData("The Roque Company: West Tower"),
    LocationName.TheRoqueCompanyWestTowerVenomLance:                LocationData("The Roque Company: West Tower"),
    LocationName.TheRoqueCompanyEastTower24500L:                    LocationData("The Roque Company: East Tower"),
    LocationName.TheRoqueCompanyEastTowerLargeSilverOre:            LocationData("The Roque Company: East Tower"),
    LocationName.TheRoqueCompanyEastTowerOliveofLifeL:              LocationData("The Roque Company: East Tower"),
    LocationName.TheRoqueCompanyEastTowerAgedWine:                  LocationData("The Roque Company: East Tower"),
    LocationName.TheRoqueCompanyEastTowerMechanicalBow:             LocationData("The Roque Company: East Tower"),
    LocationName.TheRoqueCompanyEastTowerRefreshingJam:             LocationData("The Roque Company: East Tower"),

}
    
Brightlands_Checks={
    LocationName.NewDelstaEnergizingPomegranate:                    LocationData("New Delsta"),
    LocationName.NewDelstaHealingGrape:                             LocationData("New Delsta"),
    LocationName.NewDelstaBackstreetsDagger:                        LocationData("New Delsta: Backstreets"),
    LocationName.NewDelstaBackstreetsCriticalNut:                   LocationData("New Delsta: Backstreets"),
    LocationName.NewDelstaBackstreetsInspiritingPlum:               LocationData("New Delsta: Backstreets"),
    LocationName.NewDelstaGameParlorPhysicalBelt:                   LocationData("New Delsta: Game Parlor"),
    LocationName.NewDelstaGameParlor40000L:                         LocationData("New Delsta: Game Parlor"),
    LocationName.NewDelstaGameParlorForbiddenDagger:                LocationData("New Delsta: Game Parlor"),
    LocationName.EasternNewDelstaHighroadIronBlade:                 LocationData("Eastern New Delsta Highroad"),
    LocationName.EasternNewDelstaHighroadHealingGrapeM:             LocationData("Eastern New Delsta Highroad"),
    LocationName.EasternNewDelstaHighroad700L:                      LocationData("Eastern New Delsta Highroad"),
    LocationName.NewDelstaFlatsEnergizingPomegranate:               LocationData("New Delsta Flats"),
    LocationName.NewDelstaFlatsHerbofSerenity:                      LocationData("New Delsta Flats"),
    LocationName.NewDelstaFlatsKiteShield:                          LocationData("New Delsta Flats"),
    LocationName.NewDelstaHarborAnchorageSlumberSage:               LocationData("New Delsta Harbor: Anchorage"),
    LocationName.NewDelstaHarborAnchorageBottleofPoisonDust:        LocationData("New Delsta Harbor: Anchorage"),
    LocationName.WesternClockbankHighroadInspiritingPlumBasket:     LocationData("Western Clockbank Highroad"),
    LocationName.WesternClockbankHighroadFeatheredHat:              LocationData("Western Clockbank Highroad"),
    LocationName.WesternClockbankHighroadHerbofClarity:             LocationData("Western Clockbank Highroad"),
    LocationName.SouthernClockbankHighroadLightSoulstoneM:          LocationData("Southern Clockbank Highroad"),
    LocationName.SouthernClockbankHighroadEnergizingPomegranateM:   LocationData("Southern Clockbank Highroad"),
    LocationName.SouthernClockbankHighroad6300L:                    LocationData("Southern Clockbank Highroad"),
    LocationName.SouthernClockbankHighroadMirageBow:                LocationData("Southern Clockbank Highroad"),
    LocationName.ClockbankBottleofSleepingDust:                     LocationData("Clockbank"),
    LocationName.ClockbankPointedHat:                               LocationData("Clockbank"),
    LocationName.ClockbankInspiritingPlumM:                         LocationData("Clockbank"),
    LocationName.ClockbankCrestedGreatshield:                       LocationData("Clockbank"),
    LocationName.ClockbankIndustrialDistrictHealingGrapeBunch:      LocationData("Clockbank: Industrial District"),
    LocationName.ClockbankIndustrialDistrictSlashingGlaive:         LocationData("Clockbank: Industrial District"),
    LocationName.TheRoqueCompanyFactoryEmpoweringLychee:            LocationData("The Roque Company: Factory"),
    LocationName.TheRoqueCompanyFactory7000L:                       LocationData("The Roque Company: Factory"),
    LocationName.TheRoqueCompanyFactoryProsperityCharm:             LocationData("The Roque Company: Factory"),
    LocationName.UndergroundWaterwayProtectiveRing:                 LocationData("Underground Waterway"),
    LocationName.UndergroundWaterwayHealingGrape:                   LocationData("Underground Waterway"),
    LocationName.DiamantesEstate1200L:                              LocationData("Diamantes Estate"),
    LocationName.DiamantesEstateShadowSoulstone:                    LocationData("Diamantes Estate"),
    LocationName.DiamantesEstateLongSword:                          LocationData("Diamantes Estate"),
    LocationName.DiamantesEstateInspiritingPlum:                    LocationData("Diamantes Estate"),
    LocationName.TheaterBackstageRefreshingJam:                     LocationData("Theater: Backstage"),
    LocationName.TheaterBackstageLightningAmulet:                   LocationData("Theater: Backstage"),
    LocationName.TheaterBackstageSimpleCostume:                     LocationData("Theater: Backstage"),
    LocationName.TheaterBackstageFalconKnife:                       LocationData("Theater: Backstage"),
    LocationName.TheaterBackstageHealingGrapeM:                     LocationData("Theater: Backstage"),
    LocationName.AbandonedWaterwayWrigglingRoot1:                   LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterwayHerbElixir:                       LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterwayWrigglingRoot2:                   LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterway8000L:                            LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterwayAntidoteStone:                    LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterwayWrigglingRoot3:                   LocationData("Abandoned Waterway"),
    LocationName.AbandonedWaterwayFrostAxe:                         LocationData("Abandoned Waterway"),
    LocationName.MountLiphiaDiffusingSerum:                         LocationData("Mount Liphia"),
    LocationName.MountLiphiaOliveofLifeL:                           LocationData("Mount Liphia"),
    LocationName.MountLiphiaEnergizingPomegranate:                  LocationData("Mount Liphia"),
    LocationName.MountLiphiaElementalWard:                          LocationData("Mount Liphia"),
    LocationName.MountLiphia12500L:                                 LocationData("Mount Liphia"),
    LocationName.MountLiphiaInspiritingPlumBasket:                  LocationData("Mount Liphia"),
    LocationName.SunkenMawInspiritingPlumM:                         LocationData("Sunken Maw"),
    LocationName.SunkenMawShieldofSerenity:                         LocationData("Sunken Maw"),
    LocationName.SunkenMawQuartzRod:                                LocationData("Sunken Maw"),
    LocationName.SunkenMaw13500L:                                   LocationData("Sunken Maw"),
    LocationName.OldClockTowerInfernoAmulet:                        LocationData("Old Clock Tower"),
    LocationName.OldClockTowerSeraphimSpear:                        LocationData("Old Clock Tower"),
    LocationName.DesertedHighroadDragonMail:                        LocationData("Deserted Highroad"),
    LocationName.DesertedHighroadSlumberSage:                       LocationData("Deserted Highroad"),
    LocationName.DesertedHighroadEnergizingPomegranate:             LocationData("Deserted Highroad"),
    LocationName.DesertedHighroadOliveofLifeL:                      LocationData("Deserted Highroad"),
    LocationName.LostseedCursedHelm:                                LocationData("Lostseed"),
    LocationName.LostseedReinforcingJam:                            LocationData("Lostseed"),
    LocationName.LostseedCastleEmpoweringLycheeM:                   LocationData("Lostseed Castle"),
    LocationName.LostseedCastleShadowSoulstoneL:                    LocationData("Lostseed Castle"),
    LocationName.LostseedCastleSprightlyNecklace:                   LocationData("Lostseed Castle"),
    LocationName.LostseedCastleHerbElixir:                          LocationData("Lostseed Castle"),
    LocationName.LostseedCastleUpperLevelRuinousDagger:             LocationData("Lostseed Castle: Upper Level"),
    LocationName.LostseedCastleUpperLevelEnergizingPomegranateL:    LocationData("Lostseed Castle: Upper Level"),
    LocationName.LostseedCastleUpperLevel27500L:                    LocationData("Lostseed Castle: Upper Level"),
    LocationName.LostseedCastleUpperLevelRevitalizingJam:           LocationData("Lostseed Castle: Upper Level"),
    LocationName.LostseedCastleUpperLevelLightSoulstoneM:           LocationData("Lostseed Castle: Upper Level"),

}
    
Winterlands_Checks={
    LocationName.CapeCold2000L:                                             LocationData("Cape Cold"),
    LocationName.CapeColdEnergizingPomegranate:                             LocationData("Cape Cold"),
    LocationName.EasternCapeColdSnowsNeedleDagger:                          LocationData("Eastern Cape Cold Snows"),
    LocationName.EasternCapeColdSnowsIceSoulstone:                          LocationData("Eastern Cape Cold Snows"),
    LocationName.EasternCapeColdSnowsFurCap:                                LocationData("Eastern Cape Cold Snows"),
    LocationName.EasternCapeColdSnows600L:                                  LocationData("Eastern Cape Cold Snows"),
    LocationName.SouthernCapeColdSnowsOliveofLifeM:                         LocationData("Southern Cape Cold Snows"),
    LocationName.SouthernCapeColdSnowsInspiritingPlumM:                     LocationData("Southern Cape Cold Snows"),
    LocationName.SouthernCapeColdSnowsPilgrimsRobe:                         LocationData("Southern Cape Cold Snows"),
    LocationName.SouthernCapeColdSnowsEmpoweringLychee:                     LocationData("Southern Cape Cold Snows"),
    # LocationName.BeneaththeWallStone:                                       LocationData("Beneath the Wall"),
    LocationName.CastleMeiEastTowerHerbofSerenity:                          LocationData("Castle Mei: East Tower"),
    LocationName.CastleMeiEastTowerThunderSoulstoneL:                       LocationData("Castle Mei: East Tower"),
    LocationName.CastleMeiEastTowerHealingGrapeM:                           LocationData("Castle Mei: East Tower"),
    LocationName.CastleMeiEastTowerNightmareGlaive:                         LocationData("Castle Mei: East Tower"),
    LocationName.CastleMeiEastTowerThunderstormAmulet:                      LocationData("Castle Mei: East Tower"),
    LocationName.ForbiddenShrineGleamingAmulet:                             LocationData("Forbidden Shrine"),
    LocationName.ForbiddenShrineOliveofLifeM:                               LocationData("Forbidden Shrine"),
    LocationName.ForbiddenShrineHealingGrapeM:                              LocationData("Forbidden Shrine"),
    LocationName.ForbiddenShrine15000L:                                     LocationData("Forbidden Shrine"),
    LocationName.ForbiddenShrineMagicBreaker:                               LocationData("Forbidden Shrine"),
    LocationName.InfernalCastleInspiritingPlumBasket:                       LocationData("Infernal Castle"),
    LocationName.InfernalCastleBlizzardAmulet:                              LocationData("Infernal Castle"),
    LocationName.InfernalCastleLostTribesStaff:                             LocationData("Infernal Castle"),
    LocationName.InfernalCastleEnergizingPomegranate:                       LocationData("Infernal Castle"),
    LocationName.InfernalCastleSerpentSlayer:                               LocationData("Infernal Castle"),
    LocationName.InfernalCastleStoneofTruth:                                LocationData("Infernal Castle"),
    LocationName.RuffiansHideoutBottleofBlindingDust:                       LocationData("Ruffians Hideout"),
    LocationName.RuffiansHideout1000L:                                      LocationData("Ruffians Hideout"),
    LocationName.RuffiansHideoutHereticsGreatsword:                         LocationData("Ruffians Hideout"),
    LocationName.RuffiansHideoutOliveofLifeM:                               LocationData("Ruffians Hideout"),
    LocationName.RuffiansHideoutWindRobe:                                   LocationData("Ruffians Hideout"),
    LocationName.SacredPeakAltaheReinforcingJam:                            LocationData("Sacred Peak Altahe"),
    LocationName.SacredPeakAltaheIceAmulet:                                 LocationData("Sacred Peak Altahe"),
    LocationName.SacredPeakAltaheIceSoulstoneL:                             LocationData("Sacred Peak Altahe"),
    LocationName.SacredPeakAltaheAbsoluteZeroBow:                           LocationData("Sacred Peak Altahe"),
    LocationName.SnowharesDenHealingGrapeM:                                 LocationData("Snowhares Den"),
    LocationName.SnowharesDenEmpoweringBracelet:                            LocationData("Snowhares Den"),
    LocationName.SnowharesDenQuartzDagger:                                  LocationData("Snowhares Den"),
    LocationName.SnowharesDenShadowSoulstoneM:                              LocationData("Snowhares Den"),
    LocationName.SnowharesDenInspiritingPlumM:                              LocationData("Snowhares Den"),
    LocationName.SouthernStormhailSnows15000L:                              LocationData("Southern Stormhail Snows"),
    LocationName.SouthernStormhailSnowsIceSoulstoneL:                       LocationData("Southern Stormhail Snows"),
    LocationName.SouthernStormhailSnowsRagingBeast:                         LocationData("Southern Stormhail Snows"),
    LocationName.SouthernStormhailSnowsLightningArmor:                      LocationData("Southern Stormhail Snows"),
    LocationName.SouthernStormhailSnowsHerbofRevival:                       LocationData("Southern Stormhail Snows"),
    LocationName.StormhailInspiritingPlumBasket:                            LocationData("Stormhail"),
    LocationName.StormhailKnightsArmor:                                     LocationData("Stormhail"),
    LocationName.StormhailCastleMeiThunderSoulstoneM:                       LocationData("Stormhail: Castle Mei"),
    LocationName.StormhailCastleMei16000L:                                  LocationData("Stormhail: Castle Mei"),
    LocationName.StormhailSacredGuardHeadquartersFlayersAdmonishment:       LocationData("Stormhail: Sacred Guard Headquarters"),
    LocationName.StormhailSacredGuardHeadquartersEnergizingPomegranate:     LocationData("Stormhail: Sacred Guard Headquarters"),
    LocationName.StormhailSacredGuardHeadquartersLightSoulstoneL:           LocationData("Stormhail: Sacred Guard Headquarters"),
    LocationName.WesternWinterbloomSnowsFalconRing:                         LocationData("Western Winterbloom Snows"),
    LocationName.WesternWinterbloomSnowsIceSoulstoneM:                      LocationData("Western Winterbloom Snows"),
    LocationName.WesternWinterbloomSnowsDiffusingSerum:                     LocationData("Western Winterbloom Snows"),
    LocationName.WinterbloomStrengtheningSerum:                             LocationData("Winterbloom"),
    LocationName.Winterbloom150L:                                           LocationData("Winterbloom"),
    LocationName.WinterbloomOldArmor:                                       LocationData("Winterbloom"),
    LocationName.WinterbloomHealingGrape:                                   LocationData("Winterbloom"),
    LocationName.WinterbloomIceSoulstoneM:                                  LocationData("Winterbloom"),
    LocationName.WinterbloomThievesQuartersEmpoweringLycheeM:               LocationData("Winterbloom: Thieves Quarters"),
    LocationName.FrigitIslePrisonBottleofBlindingDust:                      LocationData("Frigit Isle: Prison"),
    LocationName.FrigitIslePrisonInspiritingPlum:                           LocationData("Frigit Isle: Prison"),
    LocationName.PrisonUndergroundPassageHealingGrape:                      LocationData("Prison: Underground Passage"),
    LocationName.PrisonUndergroundPassageInspiritingPlum:                   LocationData("Prison: Underground Passage"),
    LocationName.PrisonUndergroundPassageSinnersStaff:                      LocationData("Prison: Underground Passage"),
    LocationName.PrisonUndergroundPassageAncientNecklace:                   LocationData("Prison: Underground Passage"),
    LocationName.PrisonUndergroundPassageOliveofLife:                       LocationData("Prison: Underground Passage"),
    LocationName.FrigitIsleEntranceHealingGrape:                            LocationData("Frigit Isle: Entrance"),
    LocationName.FrigitIsleAnchorageMagicNut:                               LocationData("Frigit Isle: Anchorage"),
    LocationName.FrigitIsleAnchorageInspiritingPlum:                        LocationData("Frigit Isle: Anchorage"),
    LocationName.FrigitIsleAnchorageIceSoulstone:                           LocationData("Frigit Isle: Anchorage"),

}

Wildlands_Checks={
    LocationName.OresrushLightCoinPouch:                            LocationData("Oresrush"),
    LocationName.OresrushLightNut:                                  LocationData("Oresrush"),
    LocationName.OresrushFoundryStockedGoods:                       LocationData("Oresrush: Foundry"),
    # LocationName.SilverMineHealingGrape:                            LocationData("Silver Mine"),
    LocationName.AbandonedSilverMine500L:                           LocationData("Abandoned Silver Mine"),
    LocationName.AbandonedSilverMineEnlighteningRing:               LocationData("Abandoned Silver Mine"),
    LocationName.AbandonedSilverMineLightSoulstone:                 LocationData("Abandoned Silver Mine"),
    LocationName.AbandonedSilverMineInspiritingPlum:                LocationData("Abandoned Silver Mine"),
    LocationName.GiffsManseHealingGrape:                            LocationData("Giffs Manse"),
    LocationName.GiffsManseSmallSilverOre:                          LocationData("Giffs Manse"),
    LocationName.GiffsManseBronzeShield:                            LocationData("Giffs Manse"),
    LocationName.GiffsManseLeatherHelm:                             LocationData("Giffs Manse"),
    LocationName.SouthernOresrushWildsThunderSoulstone:             LocationData("Southern Oresrush Wilds"),
    LocationName.SouthernOresrushWildsNamelessSword:                LocationData("Southern Oresrush Wilds"),
    LocationName.SouthernOresrushWilds2000L:                        LocationData("Southern Oresrush Wilds"),
    LocationName.SouthernOresrushWildsHerbofValor:                  LocationData("Southern Oresrush Wilds"),
    LocationName.CrackridgeHarborAnchorageBottleofPoisonDust:       LocationData("Crackridge Harbor: Anchorage"),
    LocationName.CrackridgeHarborAnchorageHealingGrapeM:            LocationData("Crackridge Harbor: Anchorage"),
    LocationName.CrackridgeHarborAnchorageKukri:                    LocationData("Crackridge Harbor: Anchorage"),
    LocationName.SouthernCrackridgeWildsEmpoweringLychee:           LocationData("Southern Crackridge Wilds"),
    LocationName.SouthernCrackridgeWildsHerbofClamor:               LocationData("Southern Crackridge Wilds"),
    LocationName.SouthernCrackridgeWilds6400L:                      LocationData("Southern Crackridge Wilds"),
    LocationName.SouthernCrackridgeWildsShadowSoulstoneM:           LocationData("Southern Crackridge Wilds"),
    LocationName.WesternCrackrideWildsHeadgear:                     LocationData("Western Crackride Wilds"),
    LocationName.WesternCrackrideWildsBoneMail:                     LocationData("Western Crackride Wilds"),
    LocationName.WesternCrackrideWilds8500L:                        LocationData("Western Crackride Wilds"),
    LocationName.WesternCrackrideWildsThunderSoulstoneM:            LocationData("Western Crackride Wilds"),
    LocationName.WesternCrackrideWildsInspiritingPlumBasket:        LocationData("Western Crackride Wilds"),
    LocationName.WesternCrackrideWildsOliveofLife:                  LocationData("Western Crackride Wilds"),
    LocationName.CrackridgeOliveofLifeM:                            LocationData("Crackridge"),
    LocationName.CrackridgeFromtheFarReachesofHell:                 LocationData("Crackridge"),
    LocationName.AbandonedRoadHealingGrapeM:                        LocationData("Abandoned Road"),
    LocationName.AbandonedRoad9200L:                                LocationData("Abandoned Road"),
    LocationName.AbandonedRoadBottledNightmares:                    LocationData("Abandoned Road"),
    LocationName.FellsunRuinsEnergizingPomegranateL:                LocationData("Fellsun Ruins"),
    LocationName.FellsunRuinsElementalRobe:                         LocationData("Fellsun Ruins"),
    LocationName.FellsunRuinsJadeStaff:                             LocationData("Fellsun Ruins"),
    LocationName.PathtotheBedoftheTitanEnergizingPomegranateM:      LocationData("Path to the Bed of the Titan"),
    LocationName.PathtotheBedoftheTitanProtectiveBracelet:          LocationData("Path to the Bed of the Titan"),
    LocationName.PathtotheBedoftheTitanKnightsGreatbow:             LocationData("Path to the Bed of the Titan"),
    LocationName.PathtotheBedoftheTitanFireAmulet:                  LocationData("Path to the Bed of the Titan"),
    LocationName.UnfinishedTunnel2100L:                             LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelRevitalizingJam:                   LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelOliveofLifeM:                      LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelNaturalMagnetite:                  LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelClarityStone:                      LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnel13500L:                            LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelHerbElixir:                        LocationData("Unfinished Tunnel"),
    LocationName.UnfinishedTunnelEnfeeblingAmulet:                  LocationData("Unfinished Tunnel"),
    LocationName.WesternGravellWildsEnergizingPomegranateL:         LocationData("Western Gravell Wilds"),
    LocationName.WesternGravellWildsBottleofBlindingDust:           LocationData("Western Gravell Wilds"),
    LocationName.WesternGravellWildsThunderSoulstoneL:              LocationData("Western Gravell Wilds"),
    LocationName.WesternGravellWildsHerbofSerenity:                 LocationData("Western Gravell Wilds"),
    LocationName.WesternGravellWildsStarsplitter:                   LocationData("Western Gravell Wilds"),
    LocationName.WesternGravellWilds23500L:                         LocationData("Western Gravell Wilds"),
    LocationName.GravellQuartzShield:                               LocationData("Gravell"),
    LocationName.PathtoDuskruinShrineHealingGrapeBunch:             LocationData("Path to Duskruin Shrine"),
    LocationName.PathtoDuskruinShrineAntiqueCoat:                   LocationData("Path to Duskruin Shrine"),
    LocationName.PathtoDuskruinShrineEnergizingPomegranateM:        LocationData("Path to Duskruin Shrine"),
    LocationName.DuskruinShrineOliveofLifeL:                        LocationData("Duskruin Shrine"),
    LocationName.DuskruinShrineCriticalNecklace:                    LocationData("Duskruin Shrine"),
    LocationName.DuskruinShrineIceSoulstoneL:                       LocationData("Duskruin Shrine"),
    LocationName.DuskruinShrine25000L:                              LocationData("Duskruin Shrine"),
    LocationName.DuskruinShrineDepthsEmpoweringLycheeL:             LocationData("Duskruin Shrine: Depths"),
    LocationName.DuskruinShrineDepthsAbyssalRod:                    LocationData("Duskruin Shrine: Depths"),
    LocationName.DuskruinShrineDepthsHealingGrapeBunch:             LocationData("Duskruin Shrine: Depths"),
    LocationName.DuskruinShrineDepthsShadowSoulstoneL:              LocationData("Duskruin Shrine: Depths"),
    LocationName.IvoryRavineEveningMist:                            LocationData("Ivory Ravine"),
    LocationName.IvoryRavineLostTribesAxe:                          LocationData("Ivory Ravine"),
    LocationName.IvoryRavineBottleofBefuddlingDust:                 LocationData("Ivory Ravine"),
    LocationName.IvoryRavineGiantsClub:                             LocationData("Ivory Ravine"),
    # Very weird stuff happened with Ivory Ravine: it had Sai: Eastern District's treasures data.
}
    
Leaflands_Checks={
    LocationName.CropdaleHealingGrape:                              LocationData("Cropdale"),
    LocationName.CropdaleOliveofLife:                               LocationData("Cropdale"),
    LocationName.ForestPathHealingGrape:                            LocationData("Forest Path"),
    LocationName.ForestPathWindSoulstone:                           LocationData("Forest Path"),
    LocationName.ForestPathFurArmor:                                LocationData("Forest Path"),
    LocationName.FestivalGrounds500L:                               LocationData("Festival Grounds"),
    LocationName.VeilofTreesSprightlyRing:                          LocationData("Veil of Trees"),
    LocationName.VeilofTreesHealingGrape:                           LocationData("Veil of Trees"),
    LocationName.VeilofTreesInspiritingPlum:                        LocationData("Veil of Trees"),
    LocationName.VeilofTreesSlipperyNut:                            LocationData("Veil of Trees"),
    LocationName.VeilofTreesOliveofLife:                            LocationData("Veil of Trees"),
    LocationName.AnimalTrailHerbofSerenity:                         LocationData("Animal Trail"),
    LocationName.SouthernCropdaleTrailFestivalGarland:              LocationData("Southern Cropdale Trail"),
    LocationName.SouthernCropdaleTrailHealingGrapeM:                LocationData("Southern Cropdale Trail"),
    LocationName.SouthernCropdaleTrailWindAmulet:                   LocationData("Southern Cropdale Trail"),
    LocationName.EasternCropdaleTrailRoundShield:                   LocationData("Eastern Cropdale Trail"),
    LocationName.EasternCropdaleTrailEmpoweringLychee:              LocationData("Eastern Cropdale Trail"),
    LocationName.EasternCropdaleTrail1600L:                         LocationData("Eastern Cropdale Trail"),
    LocationName.EasternCropdaleTrailSlumberSage:                   LocationData("Eastern Cropdale Trail"),
    LocationName.StarfallSpringBottleofSleepingDust:                LocationData("Starfall Spring"),
    LocationName.StarfallSpringShadowSoulstone:                     LocationData("Starfall Spring"),
    LocationName.StarfallSpringWakefulStone:                        LocationData("Starfall Spring"),
    LocationName.StarfallSpring6000L:                               LocationData("Starfall Spring"),
    LocationName.StarfallSpringHighPriestsAmulet:                   LocationData("Starfall Spring"),
    LocationName.NorthernWellgroveTrailWindSoulstoneM:              LocationData("Northern Wellgrove Trail"),
    LocationName.NorthernWellgroveTrailOliveofLifeM:                LocationData("Northern Wellgrove Trail"),
    LocationName.NorthernWellgroveTrailMagicEater:                  LocationData("Northern Wellgrove Trail"),
    LocationName.NorthernWellgroveTrailGuardsShield:                LocationData("Northern Wellgrove Trail"),
    LocationName.NorthernWellgroveTrailEnergizingPomegranateL:      LocationData("Northern Wellgrove Trail"),
    LocationName.EasternWellgroveTrailMagusKnife:                   LocationData("Eastern Wellgrove Trail"),
    LocationName.EasternWellgroveTrailRefreshingJam:                LocationData("Eastern Wellgrove Trail"),
    LocationName.EasternWellgroveTrailEmpoweringLycheeL:            LocationData("Eastern Wellgrove Trail"),
    LocationName.EasternWellgroveTrailFireSoulstoneM:               LocationData("Eastern Wellgrove Trail"),
    LocationName.EasternWellgroveTrail7200L:                        LocationData("Eastern Wellgrove Trail"),
    LocationName.WellgroveSoldiersBow:                              LocationData("Wellgrove"),
    LocationName.WellgroveAlrondsEstateEmpoweringLycheeL:           LocationData("Wellgrove: Alronds Estate"),
    LocationName.WellgroveAlrondsEstateNimbleMantle:                LocationData("Wellgrove: Alronds Estate"),
    LocationName.SecretForestLightAmulet:                           LocationData("Secret Forest"),
    LocationName.SecretForestLittleCrow:                            LocationData("Secret Forest"),
    LocationName.SecretForest10000L:                                LocationData("Secret Forest"),
    LocationName.SecretForestRefreshingJam:                         LocationData("Secret Forest"),
    LocationName.RoadtoMothersGardenHerbofValor:                    LocationData("Road to Mothers Garden"),
    LocationName.RoadtoMothersGardenStingingDagger:                 LocationData("Road to Mothers Garden"),
    LocationName.RoadtoMothersGardenInspiritingPlumM:               LocationData("Road to Mothers Garden"),
    LocationName.RoadtoMothersGardenSilentBandana:                  LocationData("Road to Mothers Garden"),
    LocationName.RoadtoMothersGardenEmpoweringLycheeL:              LocationData("Road to Mothers Garden"),
    LocationName.MothersGardenHealingGrapeBunch:                    LocationData("Mothers Garden"),
    LocationName.MothersGardenCalmingStone:                         LocationData("Mothers Garden"),
    LocationName.MothersGardenHornedHelm:                           LocationData("Mothers Garden"),
    LocationName.MothersGarden13000L:                               LocationData("Mothers Garden"),
    LocationName.MothersGardenRefreshingJam:                        LocationData("Mothers Garden"),
    LocationName.SouthernTimberainTrailRefreshingJam:               LocationData("Southern Timberain Trail"),
    LocationName.SouthernTimberainTrailHypnoSword:                  LocationData("Southern Timberain Trail"),
    LocationName.SouthernTimberainTrailEnergizingPomegranateM:      LocationData("Southern Timberain Trail"),
    LocationName.SouthernTimberainTrail3000L:                       LocationData("Southern Timberain Trail"),
    LocationName.TimberainProtectiveNecklace:                       LocationData("Timberain"),
    LocationName.TimberainCastleTownSquareWindSoulstoneL:           LocationData("Timberain Castle: Town Square"),
    LocationName.TimberainCastleTownSquareRustyPolearm:             LocationData("Timberain Castle: Town Square"),
    LocationName.TimberainCastleDiffusingSerum:                     LocationData("Timberain Castle"),
    LocationName.TimberainCastleHerbElixir:                         LocationData("Timberain Castle"),
    LocationName.TimberainCastleCleaverofDestruction:               LocationData("Timberain Castle"),
    LocationName.TimberainCastleDreamyFlower:                       LocationData("Timberain Castle"),
    LocationName.TimberainCastleRoofMagesRobe:                      LocationData("Timberain Castle: Roof"),
    LocationName.TimberainCastleRoof23000L:                         LocationData("Timberain Castle: Roof"),
    LocationName.TimberainCastleRoofDragonsHelm:                    LocationData("Timberain Castle: Roof"),
    LocationName.TimberainCastleRoofEnergizingPomegranateL:         LocationData("Timberain Castle: Roof"),
    LocationName.TimberainCastleRoofStrengtheningSerum:             LocationData("Timberain Castle: Roof"),
    LocationName.HouseWellowsManorOliveofLifeL:                     LocationData("House Wellows Manor"),
    LocationName.HouseWellowsManorCursedArmor:                      LocationData("House Wellows Manor"),
    LocationName.HouseWellowsManorHealingGrapeBunch:                LocationData("House Wellows Manor"),
    LocationName.HouseWellowsManorForbiddenAxe:                     LocationData("House Wellows Manor"),

}
    
Crestlands_Checks={
    LocationName.Flamechurch400L:                                   LocationData("Flamechurch"),
    LocationName.FlamechurchGuardsShield:                           LocationData("Flamechurch"),
    LocationName.FlamechurchHealingGrape:                           LocationData("Flamechurch"),
    LocationName.FlamechurchPilgrimsWayInspiritingPlum:             LocationData("Flamechurch Pilgrims Way"),
    LocationName.FlamechurchPilgrimsWayHealingGrape:                LocationData("Flamechurch Pilgrims Way"),
    LocationName.FlamechurchPilgrimsWayStimulatingRing:             LocationData("Flamechurch Pilgrims Way"),
    LocationName.FlamechurchPilgrimsWayToughNut:                    LocationData("Flamechurch Pilgrims Way"),
    LocationName.FlamechurchCathedralEntranceShadowSoulstone:       LocationData("Flamechurch: Cathedral Entrance"),
    LocationName.FlamechurchCathedralOliveofLife:                   LocationData("Flamechurch: Cathedral"),
    LocationName.FlamechurchCathedralLightSoulstone:                LocationData("Flamechurch: Cathedral"),
    LocationName.FlamechurchCathedralAngelsRing:                    LocationData("Flamechurch: Cathedral"),
    LocationName.CathedralCellarsLightSoulstone:                    LocationData("Cathedral Cellars"),
    LocationName.CathedralCellarsInspiritingPlum:                   LocationData("Cathedral Cellars"),
    LocationName.CathedralCellarsPilgrimRod:                        LocationData("Cathedral Cellars"),
    LocationName.EasternFlamechurchPassFurArmor:                    LocationData("Eastern Flamechurch Pass"),
    LocationName.EasternFlamechurchPassFireSoulstone:               LocationData("Eastern Flamechurch Pass"),
    LocationName.EasternFlamechurchPassEnergizingPomegranate:       LocationData("Eastern Flamechurch Pass"),
    LocationName.EasternFlamechurchPassSlumberSage:                 LocationData("Eastern Flamechurch Pass"),
    LocationName.BorderfallInspiritingPlumM:                        LocationData("Borderfall"),
    LocationName.BorderfallShadowBow:                               LocationData("Borderfall"),
    LocationName.BorderfallThunderSoulstoneM:                       LocationData("Borderfall"),
    LocationName.BorderfallEmpoweringLychee:                        LocationData("Borderfall"),
    LocationName.WesternMontwisePassGelidHelm:                      LocationData("Western Montwise Pass"),
    LocationName.WesternMontwisePass800L:                           LocationData("Western Montwise Pass"),
    LocationName.WesternMontwisePassEnergizingPomegranate:          LocationData("Western Montwise Pass"),
    LocationName.MontwiseEngagementBow:                             LocationData("Montwise"),
    LocationName.MontwiseFeatherMantle:                             LocationData("Montwise"),
    LocationName.MontwiseLibraryLapisRod:                           LocationData("Montwise: Library"),
    LocationName.MontwiseUndergroundArenaBottleofBlindingDust:      LocationData("Montwise: Underground Arena"),
    LocationName.SeatoftheWaterSpriteEnlighteningBracelet:          LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSpriteInspiritingPlumBasket:         LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSprite10000L:                        LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSpriteOliveofLifeM:                  LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSpriteBlessinginDisguise:            LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSpriteEnergizingPomegranateL:        LocationData("Seat of the Water Sprite"),
    LocationName.SeatoftheWaterSpriteRustyStaff:                    LocationData("Seat of the Water Sprite"),
    LocationName.AbandonedTraverseBottleofPoisonDust:               LocationData("Abandoned Traverse"),
    LocationName.AbandonedTraverseEnergizingPomegranate:            LocationData("Abandoned Traverse"),
    LocationName.AbandonedTraverseGuardianAmulet:                   LocationData("Abandoned Traverse"),
    LocationName.AbandonedTraverseIceSoulstoneM:                    LocationData("Abandoned Traverse"),
    LocationName.AbandonedChurchHealingGrapeBunch:                  LocationData("Abandoned Church"),
    LocationName.AbandonedChurchBlackDagger:                        LocationData("Abandoned Church"),
    LocationName.AbandonedChurchInspiritingPlumBasket:              LocationData("Abandoned Church"),
    LocationName.AbandonedChurchOliveofLifeM:                       LocationData("Abandoned Church"),
    LocationName.UndergroundLaboratory14000L:                       LocationData("Underground Laboratory"),
    LocationName.UndergroundLaboratoryBottledNightmares1:           LocationData("Underground Laboratory"),
    LocationName.UndergroundLaboratoryBottledNightmares2:           LocationData("Underground Laboratory"),
    LocationName.UndergroundLaboratoryFireSoulstoneL:               LocationData("Underground Laboratory"),
    LocationName.NorthernMontwisePassHealingGrapeM:                 LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassGoldDust1:                     LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassLargeSilverOre1:               LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassGoldDust2:                     LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassSlumberSage:                   LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassShadowSoulstoneM:              LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassLargeSilverOre2:               LocationData("Northern Montwise Pass"),
    LocationName.NorthernMontwisePassUnerringNecklace:              LocationData("Northern Montwise Pass"),
    LocationName.ForsakenGraveyardGrailofLife:                      LocationData("Forsaken Graveyard"),
    LocationName.ForsakenGraveyardVivifyingStone:                   LocationData("Forsaken Graveyard"),
    LocationName.ForsakenGraveyardDarkSlasher:                      LocationData("Forsaken Graveyard"),
    LocationName.ForsakenGraveyardFireSoulstoneL:                   LocationData("Forsaken Graveyard"),
    LocationName.ForsakenGraveyardForbiddenBlade:                   LocationData("Forsaken Graveyard"),
    LocationName.WesternMerryHillsPassHealingGrapeM:                LocationData("Western Merry Hills Pass"),
    LocationName.WesternMerryHillsPassSunShield:                    LocationData("Western Merry Hills Pass"),
    LocationName.WesternMerryHillsPassHerbofAwakening:              LocationData("Western Merry Hills Pass"),
    LocationName.WesternMerryHillsPassHerbofSerenity:               LocationData("Western Merry Hills Pass"),
    LocationName.MerryHillsEmpoweringLycheeL:                       LocationData("Merry Hills"),
    LocationName.MerryHillsHerbofClamor:                            LocationData("Merry Hills"),
    LocationName.MerryHillsShrineEntrance2700L:                     LocationData("Merry Hills: Shrine Entrance"),
    LocationName.MerryHillsShrineEntranceEmpoweringNecklace:        LocationData("Merry Hills: Shrine Entrance"),
    LocationName.ShrineofUlSterraRefreshingJam:                     LocationData("Shrine of UlSterra"),
    LocationName.ShrineofUlSterraElementalAugmentor:                LocationData("Shrine of UlSterra"),
    LocationName.ShrineofUlSterraResplendantCostume:                LocationData("Shrine of UlSterra"),
    LocationName.ShrineofUlSterraBloodstainedKnife:                 LocationData("Shrine of UlSterra"),
    LocationName.StageoftheMoonandSun24000L:                        LocationData("Stage of the Moon and Sun"),

}

Hinoeuma_Checks={
    LocationName.RyuEmpoweringLychee:                       LocationData("Ryu"),
    LocationName.NorthernRyuSandsBottleofBefuddlingDust:    LocationData("Northern Ryu Sands"),
    LocationName.NorthernRyuSandsBoneSpear:                 LocationData("Northern Ryu Sands"),
    LocationName.NorthernRyuSandsDiffusingSerum:            LocationData("Northern Ryu Sands"),
    LocationName.KuCastleTownHealingGrape:                  LocationData("Ku: Castle Town"),
    LocationName.KuCastleTownInspiritingPlum:               LocationData("Ku: Castle Town"),
    # LocationName.KuCastleTownGuard:                       LocationData("Ku: Castle Town"),   
    LocationName.CastleKuEntrance1600L:                     LocationData("Castle Ku: Entrance"),
    LocationName.CastleKuEntranceCriticalRing:              LocationData("Castle Ku: Entrance"),
    LocationName.SouthernKuSandsEnergizingPomegranate:      LocationData("Southern Ku Sands"),
    LocationName.SouthernKuSandsFireSoulstone:              LocationData("Southern Ku Sands"),
    LocationName.SouthernKuSandsHerbofLight:                LocationData("Southern Ku Sands"),
    LocationName.SouthernKuSandsInspiritingPlum:            LocationData("Southern Ku Sands"),
    LocationName.CastleKuThunderSoulstone:                  LocationData("Castle Ku"),
    LocationName.CastleKuHealingGrape:                      LocationData("Castle Ku"),
    LocationName.CastleKuFortifyingNut:                     LocationData("Castle Ku"),
    # LocationName.CastleKuOboroJournal:                    LocationData("Castle Ku"),
    LocationName.EasternSaiSandsHealingGrapeBunch:          LocationData("Eastern Sai Sands"),
    LocationName.EasternSaiSandsFireSoulstoneM:             LocationData("Eastern Sai Sands"),
    LocationName.EasternSaiSandsWarGlaive:                  LocationData("Eastern Sai Sands"),
    LocationName.EasternSaiSandsEmpoweringLycheeM:          LocationData("Eastern Sai Sands"),
    LocationName.SouthernSaiSandsHerbofLight:               LocationData("Southern Sai Sands"),
    LocationName.SouthernSaiSands6200L:                     LocationData("Southern Sai Sands"),
    LocationName.SouthernSaiSandsEnergizingPomegranateM:    LocationData("Southern Sai Sands"),
    LocationName.SouthernSaiSandsInspiritingPlumBasket:     LocationData("Southern Sai Sands"),
    LocationName.WesternSaiSandsIronShield:                 LocationData("Western Sai Sands"),
    LocationName.WesternSaiSandsOliveofLifeL:               LocationData("Western Sai Sands"),
    LocationName.WesternSaiSandsReinforcingJam:             LocationData("Western Sai Sands"),
    LocationName.SaiInspiritingPlumM:                       LocationData("Sai"),
    LocationName.SaiWindSoulstoneM:                         LocationData("Sai"),
#    LocationName.SaiEastDistrictHerbofRevival:              LocationData("Sai: East District"),
#    LocationName.SaiEastDistrictTatteredDress:              LocationData("Sai: East District"),
#    LocationName.SaiEastDistrictTatteredShoes:              LocationData("Sai: East District"),
    # LocationName.SaiEastDistrictDancerJournal:              LocationData("Sai: East District"),
#    LocationName.SaiEastDistrictBattleHatchet:              LocationData("Sai: East District"),
#    LocationName.SaiEastDistrictRefinedSword:               LocationData("Sai: East District"),
    LocationName.SandflowPassQuartzBlade:                   LocationData("Sandflow Pass"),
    LocationName.SandflowPassSteelLance:                    LocationData("Sandflow Pass"),
    LocationName.SandflowPassBoneMail:                      LocationData("Sandflow Pass"),
    LocationName.SandflowPassEmpoweringLycheeM:             LocationData("Sandflow Pass"),
    LocationName.SandflowPassStimulatingBracelet:           LocationData("Sandflow Pass"),
    LocationName.SandflowPassStrengtheningSerum:            LocationData("Sandflow Pass"),
    LocationName.OldCampsiteDualFlower:                     LocationData("Old Campsite"),
    LocationName.SandLionsDenOliveofLifeL:                  LocationData("Sand Lions Den"),
    LocationName.SandLionsDenHealingGrapeBunch:             LocationData("Sand Lions Den"),
    LocationName.SandLionsDenPoisonedHatchet:               LocationData("Sand Lions Den"),
    LocationName.SandLionsDenDiffusingSerum:                LocationData("Sand Lions Den"),
    LocationName.QuicksandGaolRustyAxe:                     LocationData("Quicksand Gaol"),
    LocationName.QuicksandGaolReinforcingJam:               LocationData("Quicksand Gaol"),
    LocationName.QuicksandGaolWindSoulstoneL:               LocationData("Quicksand Gaol"),
    LocationName.QuicksandGaolBrightStone:                  LocationData("Quicksand Gaol"),
    LocationName.QuicksandGaolScorchedBoneSpear:            LocationData("Quicksand Gaol"),
    LocationName.DragonridgeWindWhisperer:                  LocationData("Dragonridge"),
    LocationName.DragonridgeEmpoweringLychee:               LocationData("Dragonridge"),
    LocationName.DragonridgeInspiritingPlumBasket:          LocationData("Dragonridge"),
    LocationName.DragonridgeTempestAmulet:                  LocationData("Dragonridge"),
    LocationName.DecayingTempleBottleofSleepingDust:        LocationData("Decaying Temple"),
    LocationName.DecayingTempleEnergizingPomegranate:       LocationData("Decaying Temple"),
    LocationName.DecayingTemple20000L:                      LocationData("Decaying Temple"),
    LocationName.DecayingTempleFireDragonsGlaive:           LocationData("Decaying Temple"),
    LocationName.DecayingTempleSnipersBow:                  LocationData("Decaying Temple"),
    LocationName.EasternKuSandsEnergizingPomegranateL:      LocationData("Eastern Ku Sands"),
    LocationName.EasternKuSandsThunderSoulstoneL:           LocationData("Eastern Ku Sands"),
    LocationName.EasternKuSandsFirestarter:                 LocationData("Eastern Ku Sands"),
    LocationName.EasternKuSandsSlumberSage:                 LocationData("Eastern Ku Sands"),
    LocationName.EasternKuSandsHealingGrapeBunch:           LocationData("Eastern Ku Sands"),
    LocationName.TranquilGrottoOliveofLifeL:                LocationData("Tranquil Grotto"),
    LocationName.TranquilGrottoMysteriousDagger:            LocationData("Tranquil Grotto"),
    LocationName.TranquilGrottoReinforcingJam:              LocationData("Tranquil Grotto"),
    LocationName.TranquilGrotto25000L:                      LocationData("Tranquil Grotto"),

}
    
OpenSeas_Checks={
    LocationName.SunderingSeaOntheWaterDiffusingSerum:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterGimmickGoggles:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterDoubleTomahawk:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterFortuneWand:                             LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterReinforcingJam:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterHerbofSerenity:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterLeviathanGreatbow:                       LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterDualFlower:                              LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterSublimeOrnementalArmor:                  LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterInspiritingPlumBasket:                   LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWater20000L:                                  LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterBeastlyScarf:                            LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterSunkenGoldStatue:                        LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterOliveofLifeL:                            LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterStrengtheningSerum:                      LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterDualLeaf:                                LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterPlatinumShield:                          LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterInvigoratingNutL:                        LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterGoldNugget:                              LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaOntheWaterEXPAugmentor:                            LocationData("Sundering Sea: On the Water"),
    LocationName.SunderingSeaSkystone:                                          LocationData("Sundering Sea: ???"),
    LocationName.SunderingSeaDragonsScarf:                                      LocationData("Sundering Sea: ???"),
    LocationName.SunderingSeaHerbofGraceBud1:                                   LocationData("Sundering Sea: ???"),
    LocationName.SunderingSeaHerbofGraceBud2:                                   LocationData("Sundering Sea: ???"),
    LocationName.SunderingSeaHerbofGraceBud3:                                   LocationData("Sundering Sea: ???"),
    LocationName.SunderingSeaLighthouseIslandOctopuffPot:                       LocationData("Sundering Sea: Lighthouse Island"),
    LocationName.SunderingSeaLighthouseIsland12000L:                            LocationData("Sundering Sea: Lighthouse Island"),
    LocationName.SunderingSeaNamelessIsleConsciousStone:                        LocationData("Sundering Sea: Nameless Isle"),
    LocationName.SunderingSeaNamelessIsleHealingGrapeBunch:                     LocationData("Sundering Sea: Nameless Isle"),
    LocationName.SunderingSeaNamelessIsleQuartzAxe:                             LocationData("Sundering Sea: Nameless Isle"),
    LocationName.SunderingSeaNamelessIsleFinishersClaws:                        LocationData("Sundering Sea: Nameless Isle"),
    LocationName.SunderingSeaTheLostIsleAncientCursedTalisman1:                 LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleAncientCursedTalisman2:                 LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleAncientCursedTalisman3:                 LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleBlessinginDisguise:                     LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleAncientCursedTalisman4:                 LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleGreatSagesStaff:                        LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaTheLostIsleLostTribesDagger:                       LocationData("Sundering Sea: The Lost Isle"),
    LocationName.SunderingSeaShipwreckoftheEmpressInspiritingPlumBasket:        LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaShipwreckoftheEmpressThunderSoulstoneL:            LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaShipwreckoftheEmpressLostTribesSpear:              LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaShipwreckoftheEmpressCursedShield:                 LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaShipwreckoftheEmpressMasterThiefsSapphireStone:    LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaShipwreckoftheEmpressRustyDagger:                  LocationData("Sundering Sea: Shipwreck of the Empress"),
    LocationName.SunderingSeaCuriousNestHerbofSerenity:                         LocationData("Sundering Sea: Curious Nest"),
    LocationName.SunderingSeaCuriousNestLostTribesBow:                          LocationData("Sundering Sea: Curious Nest"),
    LocationName.SunderingSeaCuriousNestDecayingDragonsEssence1:                 LocationData("Sundering Sea: Curious Nest"),
    LocationName.SunderingSeaCuriousNestFangofFerocity:                         LocationData("Sundering Sea: Curious Nest"),
    LocationName.SunderingSeaCuriousNestTornadoGlaive:                          LocationData("Sundering Sea: Curious Nest"),
    LocationName.SunderingSeaCuriousNestDecayingDragonsEssence2:                 LocationData("Sundering Sea: Curious Nest"),

}
# Not included in the all_chests table
Chapter_Clears={
    LocationName.OsvaldCh1Clear:                                                LocationData("Osvald Chapter 1 Cleared"),
    LocationName.OsvaldCh2Clear:                                                LocationData("Osvald Chapter 2 Cleared"),
    LocationName.OsvaldCh3Clear:                                                LocationData("Osvald Chapter 3 Cleared"),
    LocationName.OsvaldCh4Clear:                                                LocationData("Osvald Chapter 4 Cleared"),
    LocationName.OsvaldCh5Clear:                                                LocationData("Osvald Chapter 5 Cleared"),
    LocationName.TemenosCh1Clear:                                               LocationData("Temenos Chapter 1 Cleared"),
    LocationName.TemenosCh2Clear:                                               LocationData("Temenos Chapter 2 Cleared"),
    LocationName.TemenosCh3CrackridgeClear:                                     LocationData("Temenos Chapter 3 in Crackridge Cleared"),
    LocationName.TemenosCh3StormhailClear:                                      LocationData("Temenos Chapter 3 in Stormhail Cleared"),
    LocationName.TemenosCh4Clear:                                               LocationData("Temenos Chapter 4 Cleared"),
    LocationName.ThroneCh1Clear:                                                LocationData("Throne Chapter 1 Cleared"),
    LocationName.ThroneCh2MotherClear:                                          LocationData("Throne Mother's Chapter 2 Cleared"),
    LocationName.ThroneCh2FatherClear:                                          LocationData("Throne Father's Chapter 2 Cleared"),
    LocationName.ThroneCh3MotherClear:                                          LocationData("Throne Mother's Chapter 3 Cleared"),
    LocationName.ThroneCh3FatherClear:                                          LocationData("Throne Father's Chapter 3 Cleared"),
    LocationName.ThroneCh4Clear:                                                LocationData("Throne Chapter 4 Cleared"),
    LocationName.OchetteCh1Clear:                                               LocationData("Ochette Chapter 1 Cleared"),
    LocationName.OchetteCh2ActaClear:                                           LocationData("Ochette Acta's Chapter 2 Cleared"),
    LocationName.OchetteCh2TeraClear:                                           LocationData("Ochette Tera's Chapter 2 Cleared"),
    LocationName.OchetteCh2GlacisClear:                                         LocationData("Ochette Glacis's Chapter 2 Cleared"),
    LocationName.OchetteCh3Clear:                                               LocationData("Ochette Chapter 3 Cleared"),
    LocationName.CasttiCh1Clear:                                                LocationData("Castti Chapter 1 Cleared"),
    LocationName.CasttiCh2SaiClear:                                             LocationData("Castti Chapter 2 in Sai Cleared"),
    LocationName.CasttiCh2WinterbloomClear:                                     LocationData("Castti Chapter 2 in Winterbloom Cleared"),
    LocationName.CasttiCh3Clear:                                                LocationData("Castti Chapter 3 Cleared"),
    LocationName.CasttiCh4Clear:                                                LocationData("Castti Chapter 4 Cleared"),
    LocationName.HikariCh1Clear:                                                LocationData("Hikari Chapter 1 Cleared"),
    LocationName.HikariCh2Clear:                                                LocationData("Hikari Chapter 2 Cleared"),
    LocationName.HikariCh3Clear:                                                LocationData("Hikari Chapter 3 Cleared"),
    LocationName.HikariCh4Clear:                                                LocationData("Hikari Chapter 4 Cleared"),
    LocationName.HikariCh5Clear:                                                LocationData("Hikari Chapter 5 Cleared"),
    LocationName.PartitioCh1Clear:                                              LocationData("Partitio Chapter 1 Cleared"),
    LocationName.PartitioCh2Clear:                                              LocationData("Partitio Chapter 2 Cleared"),
    LocationName.PartitioCh3Clear:                                              LocationData("Partitio Chapter 3 Cleared"),
    LocationName.PartitioCh4Clear:                                              LocationData("Partitio Chapter 4 Cleared"),
    LocationName.AgneaCh1Clear:                                                 LocationData("Agnea Chapter 1 Cleared"),
    LocationName.AgneaCh2Clear:                                                 LocationData("Agnea Chapter 2 Cleared"),
    LocationName.AgneaCh3Clear:                                                 LocationData("Agnea Chapter 3 Cleared"),
    LocationName.AgneaCh4Clear:                                                 LocationData("Agnea Chapter 4 Cleared"),
    LocationName.AgneaCh5Clear:                                                 LocationData("Agnea Chapter 5 Cleared"),
    LocationName.ThroneTemenosCh1Clear:                                         LocationData("Throne and Temenos Crossed Path Chapter 1 Cleared"),
    LocationName.ThroneTemenosCh2Clear:                                         LocationData("Throne and Temenos Crossed Path Chapter 2 Cleared"),
    LocationName.AgneaHikariCh1Clear:                                           LocationData("Agnea and Hikari Crossed Path Chapter 1 Cleared"),
    LocationName.AgneaHikariCh2Clear:                                           LocationData("Agnea and Hikari Crossed Path Chapter 2 Cleared"),
    LocationName.PartitioOsvaldCh1Clear:                                        LocationData("Partitio and Osvald Crossed Path Chapter 1 Cleared"),
    LocationName.PartitioOsvaldCh2Clear:                                        LocationData("Partitio and Osvald Crossed Path Chapter 2 Cleared"),
    LocationName.OchetteCasttiCh1Clear:                                         LocationData("Ochette and Castti Crossed Path Chapter 1 Cleared"),
    LocationName.OchetteCasttiCh2Clear:                                         LocationData("Ochette and Castti Crossed Path Chapter 2 Cleared"),
    LocationName.DefeatVide:                                                    LocationData("Defeat Vide"),

}


Game_Start={
    LocationName.GameStartChar:                                                 LocationData("Game Start Character"),
    LocationName.GameStartChapter:                                              LocationData("Game Start Chapter"),
    LocationName.GameStartRegion:                                               LocationData("Game Start Region"),
}

# Not included in the all_chests table
event_location_to_item = {
    LocationName.OsvaldCh1Clear:                                                ItemName.OsvaldCh1ClearedEvent,
    LocationName.OsvaldCh3Clear:                                                ItemName.OsvaldCh3ClearedEvent,
    LocationName.OsvaldCh4Clear:                                                ItemName.OsvaldCh4ClearedEvent,
    LocationName.OsvaldCh5Clear:                                                ItemName.OsvaldCh5ClearedEvent,
    LocationName.OsvaldStoryClear:                                              ItemName.OsvaldStoryClearedEvent,
    LocationName.TemenosCh1Clear:                                               ItemName.TemenosCh1ClearedEvent,
    LocationName.TemenosCh2Clear:                                               ItemName.TemenosCh2ClearedEvent,
    LocationName.TemenosCh3CrackridgeClear:                                     ItemName.TemenosCh3CrackridgeClearedEvent,
    LocationName.TemenosCh3StormhailClear:                                      ItemName.TemenosCh3StormhailClearedEvent,
    LocationName.TemenosCh4Clear:                                               ItemName.TemenosCh4ClearedEvent,
    LocationName.TemenosStoryClear:                                             ItemName.TemenosStoryClearedEvent,
    LocationName.ThroneCh1Clear:                                                ItemName.ThroneCh1ClearedEvent,
    LocationName.ThroneCh2MotherClear:                                          ItemName.ThroneCh2MotherClearedEvent,
    LocationName.ThroneCh2FatherClear:                                          ItemName.ThroneCh2FatherClearedEvent,
    LocationName.ThroneCh3MotherClear:                                          ItemName.ThroneCh3MotherClearedEvent,
    LocationName.ThroneCh3FatherClear:                                          ItemName.ThroneCh3FatherClearedEvent,
    LocationName.ThroneCh4Clear:                                                ItemName.ThroneCh4ClearedEvent,
    LocationName.ThroneStoryClear:                                              ItemName.ThroneStoryClearedEvent,
    LocationName.OchetteCh1Clear:                                               ItemName.OchetteCh1ClearedEvent,
    LocationName.OchetteCh2ActaClear:                                           ItemName.OchetteCh2ActaClearedEvent,
    LocationName.OchetteCh2TeraClear:                                           ItemName.OchetteCh2TeraClearedEvent,
    LocationName.OchetteCh2GlacisClear:                                         ItemName.OchetteCh2GlacisClearedEvent,
    LocationName.OchetteCh3Clear:                                               ItemName.OchetteCh3ClearedEvent,
    LocationName.OchetteStoryClear:                                             ItemName.OchetteStoryClearedEvent,
    LocationName.CasttiCh1Clear:                                                ItemName.CasttiCh1ClearedEvent,
    LocationName.CasttiCh2SaiClear:                                             ItemName.CasttiCh2SaiClearedEvent,
    LocationName.CasttiCh2WinterbloomClear:                                     ItemName.CasttiCh2WinterbloomClearedEvent,
    LocationName.CasttiCh3Clear:                                                ItemName.CasttiCh3ClearedEvent,
    LocationName.CasttiCh4Clear:                                                ItemName.CasttiCh4ClearedEvent,
    LocationName.CasttiStoryClear:                                              ItemName.CasttiStoryClearedEvent,
    LocationName.HikariCh1Clear:                                                ItemName.HikariCh1ClearedEvent,
    LocationName.HikariCh2Clear:                                                ItemName.HikariCh2ClearedEvent,
    LocationName.HikariCh3Clear:                                                ItemName.HikariCh3ClearedEvent,
    LocationName.HikariCh4Clear:                                                ItemName.HikariCh4ClearedEvent,
    LocationName.HikariCh5Clear:                                                ItemName.HikariCh5ClearedEvent,
    LocationName.HikariStoryClear:                                              ItemName.HikariStoryClearedEvent,
    LocationName.PartitioCh1Clear:                                              ItemName.PartitioCh1ClearedEvent,
    LocationName.PartitioCh2Clear:                                              ItemName.PartitioCh2ClearedEvent,
    LocationName.PartitioCh3Clear:                                              ItemName.PartitioCh3ClearedEvent,
    LocationName.PartitioCh4Clear:                                              ItemName.PartitioCh4ClearedEvent,
    LocationName.PartitioSaiClear:                                              ItemName.PartitioSaiClearedEvent,
    LocationName.PartitioWinterbloomClear:                                      ItemName.PartitioWinterbloomClearedEvent,
    LocationName.PartitioTropuhopuClear:                                        ItemName.PartitioTropuhopuClearedEvent,
    LocationName.PartitioStoryClear:                                            ItemName.PartitioStoryClearedEvent,
    LocationName.AgneaCh1Clear:                                                 ItemName.AgneaCh1ClearedEvent,
    LocationName.AgneaCh2Clear:                                                 ItemName.AgneaCh2ClearedEvent,
    LocationName.AgneaCh3Clear:                                                 ItemName.AgneaCh3ClearedEvent,
    LocationName.AgneaCh4Clear:                                                 ItemName.AgneaCh4ClearedEvent,
    LocationName.AgneaCh5Clear:                                                 ItemName.AgneaCh5ClearedEvent,
    LocationName.AgneaStoryClear:                                               ItemName.AgneaStoryClearedEvent,
    LocationName.ThroneTemenosCh1Clear:                                         ItemName.TemenosThroneCh1ClearedEvent,
    LocationName.ThroneTemenosCh2Clear:                                         ItemName.TemenosThroneCh2ClearedEvent,
    LocationName.AgneaHikariCh1Clear:                                           ItemName.HikariAgneaCh1ClearedEvent,
    LocationName.AgneaHikariCh2Clear:                                           ItemName.HikariAgneaCh2ClearedEvent,
    LocationName.PartitioOsvaldCh1Clear:                                        ItemName.OsvaldPartitioCh1ClearedEvent,
    LocationName.PartitioOsvaldCh2Clear:                                        ItemName.OsvaldPartitioCh2ClearedEvent,
    LocationName.OchetteCasttiCh1Clear:                                         ItemName.CasttiOchetteCh1ClearedEvent,
    LocationName.OchetteCasttiCh2Clear:                                         ItemName.CasttiOchetteCh2ClearedEvent,
    LocationName.DefeatVide:                                                    ItemName.VideDefeatedEvent,
    LocationName.TravelersBagClear:                                             ItemName.TravelersBagClearedEvent,
    LocationName.PeculiarTomesClear:                                            ItemName.PeculiarTomesClearedEvent,
    LocationName.FromTheFarReachesOfHellClear:                                  ItemName.FromTheFarReachesOfHellClearedEvent,
    LocationName.GalderaDefeated:                                               ItemName.GalderaDefeatedEvent,
   
}

all_chests = {
    **Totohaha_Checks,
    **Harborlands_Checks,
    **Brightlands_Checks,
    **Winterlands_Checks,
    **Wildlands_Checks,
    **Leaflands_Checks,
    **Crestlands_Checks,
    **Hinoeuma_Checks,
    **OpenSeas_Checks,
    **Game_Start
}
